### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by darkphan** [PrinceOfAmber/DecoLayers#1]
Minecraft version & Mod Version:

Minecraft: 1.12.2
Block Layering: 1.0.1

Single player or Server:

Server

Describe problem (what you were doing / what happened):

Starting Server. :)

Crash log (if any):

Crash log: https://pste.me/#/1NEQV

**Comment by Lothrazar** [comment]
Thanks for the report, apparently this has been in there for a while and i never checked. This fixes it for my localhost server so it should work

https://minecraft.curseforge.com/projects/block-layers/files/2684305
